name: "Noff's Portfolio"
description: "Product Designer and prototyper at Uber in San Francisco."

# this should eventually be set to my domain
url: "http://noff.me/"

paginate: 10

markdown: rdiscount
permalink: none
highlight: pigments
