name: "Portfolio v2"
description: "A slight facelift and Jekyll blog to boot."

# this should eventually be set to my domain
url: "http://localhost:4000"

paginate: 10

markdown: rdiscount
permalink: pretty
highlight: pigments
